### ISSUE TITLE
Release first version on Clojars

### ISSUE THREAD

**Issue by ftomassetti** [ftomassetti/effectivejava#40]
And explain how to use it in the Readme.

What should we do to make it usable from Maven?

**Comment by ftomassetti** [comment]
Before releasing v0.1.3 we should update the changelog. @davidor did I miss anything?

Then we should add a tag and upload to clojars

**Comment by davidor** [comment]
Looks good to me.

**Comment by ftomassetti** [comment]
And it should be done: https://clojars.org/effectivejava

Probably this code is going to be used as a standalone utility and not a library so for now I am not documenting it in the README.
