### ISSUE TITLE
Command not implemented in interactive mode closes program

### ISSUE THREAD

**Issue by davidor** [ftomassetti/effectivejava#58]
In the interactive mode, ff the user tries to execute a command that is not implemented, he gets an error such as: Command not implemented:  <name-of-command>, and the program closes.

I think that it would be more natural to show the error and continue the execution.

**Comment by ftomassetti** [comment]
I definitely agree with that. We should probably think also of tests for these issues.

**Comment by davidor** [comment]
This should be solved in #56 . I agree, there are some parts of the code, like the interactive mode, that do not have tests.

**Comment by ftomassetti** [comment]
This should be fixed, so I will close it. Thanks David!
